import { createConstants } from '../utils';

export default createConstants(
  'GET_USERS',
  'GET_USERS_ERROR',
  'GET_USERS_SUCCESS',
  'GET_PRECINCTS',
  'GET_PRECINCTS_ERROR',
  'GET_PRECINCTS_SUCCESS',
  'DOWNLOAD_CSV',
  'DOWNLOAD_CSV_ERROR',
  'DOWNLOAD_CSV_SUCCESS',
  'UPLOAD_CSV',
  'UPLOAD_CSV_ERROR',
  'UPLOAD_CSV_SUCCESS',
  'ADD_USER',
  'ADD_USER_ERROR',
  'ADD_USER_SUCCESS',
  'REMOVE_USER',
  'REMOVE_USER_ERROR',
  'REMOVE_USER_SUCCESS'
);
