import { createConstants } from '../utils';

export default createConstants(
  'SET_ATTENDEES',
  'SET_SUPPORTERS',
  'GET_PRECINCT_REQUEST',
  'GET_PRECINCT_SUCCESS',
  'GET_PRECINCT_FAILURE',
  'UPDATE_ATTENDEES_REQUEST',
  'UPDATE_ATTENDEES_SUCCESS',
  'UPDATE_ATTENDEES_FAILURE',
  'UPDATE_VIABILITY_COUNTS_REQUEST',
  'UPDATE_VIABILITY_COUNTS_SUCCESS',
  'UPDATE_VIABILITY_COUNTS_FAILURE',
  'UPDATE_APPORTIONMENT_COUNTS_REQUEST',
  'UPDATE_APPORTIONMENT_COUNTS_SUCCESS',
  'UPDATE_APPORTIONMENT_COUNTS_FAILURE'
);
