import { createConstants } from '../utils';

export default createConstants(
  'CREATE_REPORT_REQUEST',
  'CREATE_REPORT_SUCCESS',
  'CREATE_REPORT_FAILURE',
  'UPDATE_REPORT_REQUEST',
  'UPDATE_REPORT_SUCCESS',
  'UPDATE_REPORT_FAILURE',
  'REMOVE_REPORT_REQUEST',
  'REMOVE_REPORT_SUCCESS',
  'REMOVE_REPORT_FAILURE',
  'SET_ATTR',
  'RESET'
);
